import { Reducer } from 'umi';
import { queryStatistics } from './service';
import { Effect } from '@@/plugin-dva/connect';
import { TData, TDetail, TState, TStatistic, TTab } from './data';
import moment from 'moment';

export type TDashboardModel = {
  namespace: string;
  // state: TDashboardState,
  state: TState;
  reducers: {
    changeRange: Reducer<TState>;
    changeSelect: Reducer<TState>;
    changeTab: Reducer<TState>;
    updateDashboard: Reducer<TState>;
    updateSummaryDataList: Reducer<TState>;
  };
  effects: {
    queryStatistics: Effect;
  };
};

const DashboardModel: TDashboardModel = {
  namespace: 'dashboard',
  // state: {
  //   timeQuantum: '', // 时间段
  //   summaryList: [],
  //   strategySummary: {
  //     targetList: [],
  //     gainList: [],
  //     relocationList: [],
  //     keepList: []
  //   },
  //   strategyDetail: {
  //     activeTabKey: 'tab1',
  //     tabList: [
  //       {
  //         key: 'tab1',
  //         tab: '获得',
  //       },
  //       {
  //         key: 'tab2',
  //         tab: '重新定位',
  //       },
  //       {
  //         key: 'tab3',
  //         tab: '保留',
  //       },
  //     ],
  //     strategyDetailList: []
  //   }
  // },

  state: {
    rangeValues: [moment().subtract(30, 'days'), moment()], // todo 初始化时间范围
    target1: 'pfee',
    target2: 'approas',
    activeTabKey: 'tab1',
    targetList: [
      {
        name: '每结果成本',
        value: 'pfee',
      },
      {
        name: '移动应用回报率',
        value: 'approas',
      },
      {
        name: '消费金额',
        value: 'spent',
      },
      {
        name: '点击率',
        value: 'ctr',
      },
      {
        name: '频率',
        value: 'frequency',
      },
      {
        name: '费用/前次',
        value: 'cpm',
      },
      {
        name: '出站点击率',
        value: 'octr',
      },
      {
        name: '出站点击数',
        value: 'oclicks',
      },
      {
        name: '每次点击费用',
        value: 'cpc',
      },
      {
        name: '安装数',
        value: 'installs',
      },
      // {
      //   name: '每次安装费用',
      //   value: 'installfee'
      // }, // installfee暂时为null
    ],
    tabList: [],
    totalList: [],
    detailDataList: [],
  },
  reducers: {
    changeRange(state, { payload }) {
      return {
        ...state,
        rangeValues: payload.dates,
      };
    },
    changeSelect(state, { payload }) {
      return {
        ...state,
        [payload.target]: payload.value,
      };
    },
    changeTab(state, { payload }) {
      // console.log('payload', payload);
      // console.log('state', JSON.stringify(state));
      // const res = {...state};
      // if (res.strategyDetail) {
      //   res.strategyDetail.activeTabKey = payload.activeTabKey;
      // }
      // return res;
      return {
        ...state,
        activeTabKey: payload.activeTabKey,
      };
    },
    updateDashboard(state, { payload }) {
      // console.log('updateDashboard', JSON.stringify(payload));
      const targetList = [
        'pfee',
        'approas',
        'spent',
        'ctr',
        'frequency',
        'cpm',
        'octr',
        'oclicks',
        'cpc',
        'installs',
      ];

      const data: TState = {
        ...state,
        totalList: payload.totalList,
      };
      // todo: 构造数据
      // todo: 给data.detailList赋值假数据
      if (Array.isArray(payload.detailList)) {
        const tabList: TTab[] = [];
        const detailDataList: TData[][] = [];
        payload.detailList.forEach((d: TDetail, idx: number) => {
          // todo: 构造tabList
          const tab: TTab = {
            key: `tab${idx + 1}`,
            tab: d.name,
          };
          tabList.push(tab);

          const dMergeList: TStatistic[] = [];
          const xListMap: Record<string, TStatistic> = {};
          d.list.forEach((s) => {
            if (!xListMap[s.createdDate]) {
              xListMap[s.createdDate] = s;
              targetList.forEach((t) => {
                // todo: 如果数据区间过大，需要将数据累加压缩
                xListMap[s.createdDate][t] = parseFloat(s[t]);
              });
            } else if (data.targetList) {
              const statistic = xListMap[s.createdDate];
              data.targetList.forEach((o) => {
                // todo: 如果数据区间过大，需要将数据累加压缩
                statistic[o.value] += parseFloat(o.value) + parseFloat(s[o.value]);
              });
            }
          });

          Object.values(xListMap).forEach((value) => {
            dMergeList.push(value);
          });

          const dList: TData[] = [];
          // const xList: string[] = []; // 记录list中的所有时间点
          dMergeList.forEach((s) => {
            // todo: 构造用于绘图的数组
            if (data.targetList) {
              data.targetList.forEach((o) => {
                // todo: 如果数据区间过大，需要将数据累加压缩
                const dt: TData = {
                  x: s.createdDate,
                  y: s[o.value],
                  target: o.name,
                  targetValue: o.value,
                };
                dList.push(dt);
              });
            }

            // if (xList.indexOf(s.createdDate) === -1) {
            //   xList.push(s.createdDate);
            // }
          });

          // todo: 合并dList中x,和target相同的项
          // const dataList: TData[][] = [];
          // for (const x of xList) {
          //   dList.forEach((dt) => {
          //     if (dt.x === x && dt.)
          //   })
          // }
          detailDataList.push(dList);

          data.detailDataList = detailDataList;

          // todo: 根据detailDataList更新summaryDataList
        });
        data.tabList = tabList;
      }

      return data;
    },
    updateSummaryDataList(state, { payload }) {
      const data: TState = {
        ...state,
        ...payload,
      };

      // todo 根据detailDataList生成summaryDataList

      return data;
    },
  },
  effects: {
    *queryStatistics({ payload }, { call, put }) {
      // console.log('effects', payload)
      const response = yield call(queryStatistics, payload);
      // console.log('errects', JSON.stringify(response))
      // clicks oclicks installs 需要返回数值类型
      yield put({
        type: 'updateDashboard',
        payload: {
          totalList: response[0].data,
          // todo: 赋值detailList,inputoutput
          // detailList: response[1].data,
          detailList: [
            {
              name: '11',
              id: 12,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
            {
              name: '33',
              id: 33,
              list: [
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-01',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '15',
                  pfee: 20,
                  approas: 35,
                  spent: 55,
                  ctr: 10,
                  frequency: 15,
                  cpm: 5,
                  octr: 30,
                  oclicks: '35',
                  cpc: 10,
                  installs: '5',
                  installfee: null,
                  createdDate: '2021-01-02',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '145',
                  pfee: 100,
                  approas: 115,
                  spent: 105,
                  ctr: 200,
                  frequency: 300,
                  cpm: 250,
                  octr: 150,
                  oclicks: '155',
                  cpc: 140,
                  installs: '120',
                  installfee: null,
                  createdDate: '2021-01-03',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '85',
                  pfee: 50,
                  approas: 75,
                  spent: 25,
                  ctr: 60,
                  frequency: 50,
                  cpm: 125,
                  octr: 70,
                  oclicks: '80',
                  cpc: 50,
                  installs: '60',
                  installfee: null,
                  createdDate: '2021-01-04',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '60',
                  pfee: 20,
                  approas: 35,
                  spent: 10,
                  ctr: 40,
                  frequency: 60,
                  cpm: 50,
                  octr: 100,
                  oclicks: '110',
                  cpc: 80,
                  installs: '40',
                  installfee: null,
                  createdDate: '2021-01-05',
                },
                {
                  name: null,
                  id: null,
                  resultName: null,
                  results: '0',
                  reach: '0',
                  impression: '0',
                  clicks: '45',
                  pfee: 10,
                  approas: 15,
                  spent: 5,
                  ctr: 20,
                  frequency: 30,
                  cpm: 25,
                  octr: 50,
                  oclicks: '55',
                  cpc: 40,
                  installs: '20',
                  installfee: null,
                  createdDate: '2021-01-06',
                },
              ],
            },
          ],
        },
      });
    },
  },
};

export default DashboardModel;
