export interface AdvPackParam {
    current: number,
    size: number,
    appName: string,
    startT: string,
    endT: string
}
export interface AdvSetParam {
    current: number,
    size: number,
    setName: string,
    startT: string,
    endT: string
}
export interface AdvAdvParam {
    current: number,
    size: number,
    advName: string,
    startT: string,
    endT: string
}

export interface AdvParam {
    fdId: string,
    state: string
}
export interface AdvPackListType{
    appName: string,
    approas: number,
    brandName: string,
    brandVal: string,
    budget: string,
    clicks: string,
    cpc: number,
    cpm: number,
    createtime: string,
    ctr: number,
    delFlag: string,
    fbId: string,
    frequency: string,
    impression: string,
    installName: string,
    installVal: string,
    installfee: string,
    installs: string,
    oclicks: string,
    octr: number,
    packId: number,
    pfee: number,
    reach: string,
    resultName: string,
    results: string,
    spendName: string,
    spendNum: string,
    spendVal: string,
    spent: number,
    state: string,
    status: string,
    statusDesc: string,
    targetName: string,
    targetVal: string,
    tokenId: number,
    updatetime: string,
    loading?:boolean
}

export interface AdvSetListType{
    setId:number,
    setName: string,
    appName:string,
    approas: number,
    brandName: string,
    brandVal: string,
    budget: string,
    clicks: string,
    cpc: number,
    cpm: number,
    createtime: string,
    ctr: number,
    delFlag: string,
    fbId: string,
    frequency: string,
    impression: string,
    installName: string,
    installVal: string,
    installfee: string,
    installs: string,
    oclicks: string,
    octr: number,
    packId: number,
    pfee: number,
    reach: string,
    resultName: string,
    results: string,
    spendName: string,
    spendNum: string,
    spendVal: string,
    spent: number,
    state: string,
    status: string,
    statusDesc: string,
    targetName: string,
    targetVal: string,
    tokenId: number,
    updatetime: string,
    loading?:boolean
}
export interface AdvAdvListType{
    advName: string,
    advId: number,
    approas: number,
    brandName: string,
    brandVal: string,
    budget: string,
    clicks: string,
    cpc: number,
    cpm: number,
    createtime: string,
    ctr: number,
    delFlag: string,
    fbId: string,
    frequency: string,
    impression: string,
    installName: string,
    installVal: string,
    installfee: string,
    installs: string,
    oclicks: string,
    octr: number,
    packId: number,
    pfee: number,
    reach: string,
    resultName: string,
    results: string,
    spendName: string,
    spendNum: string,
    spendVal: string,
    spent: number,
    state: string,
    status: string,
    statusDesc: string,
    targetName: string,
    targetVal: string,
    tokenId: number,
    updatetime: string,
    imgTextList:Array<any>,
    loading?:boolean
}
export interface AdvData {
    advPackList: AdvPackListType[],
    advSetList: AdvSetListType[],
    advAdvList: AdvAdvListType[],
    advSetListForTreeView:AdvSetListType[],
    advAdvListForTreeView:AdvAdvListType[],
    advPackTotal:number,
    advSetTotal:number,
    advAdvTotal:number
}

